### ISSUE TITLE
The steps on how to do it

### ISSUE THREAD

**Issue by JohnHour89** [miguelmota/loopback-file-upload-example#2]
Hi, may I know can explain or elaborate more steps on how to do it? I want to do it like using the POSTMAN or in the client side there. Thank you.

**Comment by miguelmota** [comment]
Hi @JohnHour89 , here's a similar questions already answered here in [issue #1](https://github.com/miguelmota/loopback-file-upload-example/issues/1)

**Comment by JohnHour89** [comment]
Hi, What I mean is got any other alternative ways of upload the files with the data, because I got try the curl method and using the POSTMAN it could not any response? This is way how you doing the things without answer the question totally and close the issue?
